"""Anchor-preserving AIG lowering and original fault-to-anchor mapping."""

from dataclasses import dataclass
import hashlib
import json
from pathlib import Path
import random
import re

import numpy as np

from .circuit import Circuit, build_graph, read_bench
from .features import compose_fault_embeddings


SCHEMA = "anchor_aig_map_v1"
CONVERTER = "generate_anchor_aig_v1"
HELPER_PREFIX = "__anchor_aig_"
SUPPORTED_SOURCE_KINDS = {"AND", "NAND", "OR", "NOR", "NOT", "BUF"}
AUDIT_PATH_FIELDS = frozenset({"source_bench", "aig_bench"})


def sha256(path):
    digest = hashlib.sha256()
    with Path(path).open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


@dataclass(frozen=True)
class LoweredAig:
    text: str
    source: Circuit
    helper_origins: dict


def lower_to_anchor_aig(source_path):
    """Lower one binary BENCH to AND/NOT without merging original signals."""
    source_path = Path(source_path).resolve()
    source = read_bench(source_path)
    source_signals = set(source.inputs) | set(source.gates)
    collisions = sorted(name for name in source_signals if name.startswith(HELPER_PREFIX))
    if collisions:
        raise ValueError(
            "Source uses reserved anchor-AIG helper prefix: {}".format(collisions[0])
        )
    unsupported = sorted(
        {gate.kind for gate in source.gates.values()} - SUPPORTED_SOURCE_KINDS
    )
    if unsupported:
        raise ValueError("Unsupported source gate for anchor AIG: {}".format(unsupported[0]))

    lines = [
        "# Anchor-preserving AND/NOT BENCH generated by {}".format(CONVERTER),
        "# Source: {}".format(source_path.name),
        "# Original signal names are anchors; __anchor_aig_* nodes are helpers.",
        "",
    ]
    lines.extend("INPUT({})".format(name) for name in source.inputs)
    lines.append("")
    lines.extend("OUTPUT({})".format(name) for name in source.outputs)
    lines.append("")

    helper_origins = {}
    helper_counter = 0

    def helper(origin, kind, pins):
        nonlocal helper_counter
        name = "{}{:08d}".format(HELPER_PREFIX, helper_counter)
        helper_counter += 1
        helper_origins[name] = origin
        lines.append("{} = {}({})".format(name, kind, ", ".join(pins)))
        return name

    for name in source.order:
        gate = source.gates[name]
        pins = list(gate.inputs)
        if gate.kind == "AND":
            lines.append("{} = AND({})".format(name, ", ".join(pins)))
        elif gate.kind == "NOT":
            lines.append("{} = NOT({})".format(name, pins[0]))
        elif gate.kind == "NAND":
            conjunction = helper(name, "AND", pins)
            lines.append("{} = NOT({})".format(name, conjunction))
        elif gate.kind == "OR":
            first = helper(name, "NOT", [pins[0]])
            second = helper(name, "NOT", [pins[1]])
            conjunction = helper(name, "AND", [first, second])
            lines.append("{} = NOT({})".format(name, conjunction))
        elif gate.kind == "NOR":
            first = helper(name, "NOT", [pins[0]])
            second = helper(name, "NOT", [pins[1]])
            lines.append("{} = AND({}, {})".format(name, first, second))
        elif gate.kind == "BUF":
            inverse = helper(name, "NOT", [pins[0]])
            lines.append("{} = NOT({})".format(name, inverse))
        else:  # guarded above; keep this fail-closed if the parser changes.
            raise ValueError("Unsupported source gate for anchor AIG: {}".format(gate.kind))
    lines.append("")
    return LoweredAig("\n".join(lines), source, helper_origins)


def _evaluate(circuit, input_values, mask):
    values = dict(input_values)
    for name in circuit.order:
        gate = circuit.gates[name]
        pins = [values[pin] for pin in gate.inputs]
        if gate.kind == "AND":
            value = pins[0] & pins[1]
        elif gate.kind == "NAND":
            value = (~(pins[0] & pins[1])) & mask
        elif gate.kind == "OR":
            value = pins[0] | pins[1]
        elif gate.kind == "NOR":
            value = (~(pins[0] | pins[1])) & mask
        elif gate.kind == "NOT":
            value = (~pins[0]) & mask
        elif gate.kind == "BUF":
            value = pins[0]
        else:
            raise ValueError("Cannot evaluate gate type {}".format(gate.kind))
        values[name] = value
    return values


def verify_anchor_equivalence(source, aig, vectors=256, seed=14):
    """Compare every original signal to its same-name AIG anchor."""
    if vectors <= 0:
        raise ValueError("vectors must be positive")
    if source.inputs != aig.inputs or source.outputs != aig.outputs:
        raise ValueError("Anchor AIG changed primary inputs or outputs")
    missing = sorted((set(source.inputs) | set(source.gates)) -
                     (set(aig.inputs) | set(aig.gates)))
    if missing:
        raise ValueError("Anchor AIG is missing original signal {}".format(missing[0]))
    if set(gate.kind for gate in aig.gates.values()) - {"AND", "NOT"}:
        raise ValueError("Anchor AIG contains a non-AND/NOT gate")

    rng = random.Random(seed)
    remaining = vectors
    original_signals = source.inputs + source.order
    while remaining:
        width = min(64, remaining)
        mask = (1 << width) - 1
        inputs = {name: rng.getrandbits(width) for name in source.inputs}
        source_values = _evaluate(source, inputs, mask)
        aig_values = _evaluate(aig, inputs, mask)
        for name in original_signals:
            if source_values[name] != aig_values[name]:
                raise ValueError("Anchor AIG mismatch at original signal {}".format(name))
        remaining -= width


def build_aigmap(source_path, aig_path, lowered, graph, recorded_aig_path=None):
    """Build the sidecar after the AIG file has been parsed and hashed."""
    source_path, aig_path = Path(source_path).resolve(), Path(aig_path).resolve()
    recorded_aig_path = Path(recorded_aig_path or aig_path).resolve()
    signals = {}
    for name in lowered.source.inputs:
        signals[name] = {
            "anchor_name": name,
            "anchor_node": int(graph["anchors"][name]),
            "origin_kind": "INPUT",
        }
    for name in lowered.source.order:
        signals[name] = {
            "anchor_name": name,
            "anchor_node": int(graph["anchors"][name]),
            "origin_kind": lowered.source.gates[name].kind,
        }
    helpers = [
        {
            "name": name,
            "node": int(graph["anchors"][name]),
            "origin": lowered.helper_origins[name],
        }
        for name in sorted(lowered.helper_origins)
    ]
    boundaries = {
        name: {
            "kind": alias["kind"],
            "signal": alias["signal"],
            "anchor_node": int(alias["anchor"]),
        }
        for name, alias in graph["boundary_aliases"].items()
    }
    return {
        "schema": SCHEMA,
        "converter": CONVERTER,
        "source_bench": str(source_path),
        "source_bench_sha256": sha256(source_path),
        "aig_bench": str(recorded_aig_path),
        "aig_bench_sha256": sha256(aig_path),
        "aig_graph_sha256": graph["graph_sha256"],
        "feature_node_count": len(graph["nodes"]),
        "inputs": list(lowered.source.inputs),
        "outputs": list(lowered.source.outputs),
        "signals": signals,
        "helpers": helpers,
        "boundaries": boundaries,
    }


def resolve_original_faults(catalog, source, graph):
    """Map every original PODEM catalog row to DeepGate feature-graph anchors."""
    records = []
    seen = set()
    source_signals = set(source.inputs) | set(source.gates)
    for row, item in enumerate(catalog.get("faults", [])):
        fault_id = str(item["fault_id"])
        if fault_id in seen:
            raise ValueError("Duplicate original fault ID {}".format(fault_id))
        seen.add(fault_id)
        node_name = str(item["node_name"])
        input_wire = str(item["input_wire_name"])
        io_value = int(item["io"])
        sa_value = int(item["fault_type"])
        eqv_fault_num = int(item["eqv_fault_num"])
        if io_value not in (0, 1) or sa_value not in (0, 1) or eqv_fault_num <= 0:
            raise ValueError("Invalid original fault attributes for {}".format(fault_id))
        identity = re.fullmatch(
            r"(.+):(GO|GI(\d+)):sa([01])(?:@dup(\d+))?", fault_id
        )
        if identity is None:
            raise ValueError("Invalid original fault ID {}".format(fault_id))
        identity_node, identity_io, identity_pin, identity_sa, duplicate = identity.groups()
        expected_io = "GO" if io_value == 1 else "GI{}".format(int(item["input_index"]))
        if (identity_node != node_name or identity_io != expected_io
                or int(identity_sa) != sa_value):
            raise ValueError("Fault identity fields disagree for {}".format(fault_id))
        if duplicate is not None and int(duplicate) <= 0:
            raise ValueError("Invalid duplicate suffix for {}".format(fault_id))

        alias = graph["boundary_aliases"].get(node_name)
        if alias is not None:
            if io_value == 1:
                if (alias["kind"] != "INPUT" or input_wire != "-"
                        or int(item["input_index"]) != -1
                        or int(item["input_occurrence"]) != -1):
                    raise ValueError("Invalid PI boundary fault {}".format(fault_id))
                receiver_anchor = connected_anchor = int(alias["anchor"])
                source_signal = alias["signal"]
            else:
                if (alias["kind"] != "OUTPUT" or input_wire != alias["signal"]
                        or int(item["input_index"]) != 0
                        or int(item["input_occurrence"]) != 0):
                    raise ValueError("Invalid PO boundary fault {}".format(fault_id))
                receiver_anchor = int(alias["anchor"])
                connected_anchor = int(graph["anchors"][input_wire])
                source_signal = input_wire
        elif node_name in source_signals:
            receiver_anchor = int(graph["anchors"][node_name])
            if io_value == 1:
                if (input_wire != "-" or int(item["input_index"]) != -1
                        or int(item["input_occurrence"]) != -1):
                    raise ValueError("Invalid GO fault {}".format(fault_id))
                connected_anchor = receiver_anchor
                source_signal = node_name
            else:
                pin_index = int(item["input_index"])
                atpg_inputs = source.atpg_inputs(node_name)
                if (pin_index < 0 or pin_index >= len(atpg_inputs)
                        or atpg_inputs[pin_index] != input_wire):
                    raise ValueError("GI fault does not identify an actual receiver pin: {}".format(fault_id))
                occurrence = sum(
                    pin == input_wire for pin in atpg_inputs[:pin_index]
                )
                if int(item["input_occurrence"]) != occurrence:
                    raise ValueError("GI input occurrence mismatch for {}".format(fault_id))
                connected_anchor = int(graph["anchors"][input_wire])
                source_signal = input_wire
        else:
            raise ValueError("Original fault node has no AIG anchor: {}".format(fault_id))

        records.append({
            "fault_id": fault_id,
            "catalog_row": row,
            "original_gate": node_name,
            "source_signal": source_signal,
            "io": "GO" if io_value == 1 else "GI",
            "original_pin_index": int(item.get("input_index", -1)),
            "input_occurrence": int(item.get("input_occurrence", -1)),
            "sa_value": sa_value,
            "eqv_fault_num": eqv_fault_num,
            "gate_function_anchor_node": receiver_anchor,
            "connected_function_anchor_node": connected_anchor,
        })

    uncollapsed_total = int(catalog.get("uncollapsed_total", -1))
    if not records:
        raise ValueError("Original fault catalog is empty")
    if sum(record["eqv_fault_num"] for record in records) != uncollapsed_total:
        raise ValueError("Original fault equivalence counts do not match total")
    return records


def compose_original_fault_embeddings(gate_hf, fault_records):
    features = compose_fault_embeddings(gate_hf, fault_records)
    if features.shape != (len(fault_records), 257):
        raise ValueError("Original fault embeddings must have shape [fault_count, 257]")
    if not np.isfinite(features).all():
        raise ValueError("Original fault embeddings contain non-finite values")
    return features


def validate_aigmap(mapping, source_path, aig_path, graph, expected_aig_path=None):
    """Fail closed if a sidecar is stale or incomplete."""
    source_path, aig_path = Path(source_path).resolve(), Path(aig_path).resolve()
    expected_aig_path = Path(expected_aig_path or aig_path).resolve()
    if mapping.get("schema") != SCHEMA or mapping.get("converter") != CONVERTER:
        raise ValueError("Unsupported anchor AIG mapping schema")
    expected = {
        "source_bench_sha256": sha256(source_path),
        "aig_bench_sha256": sha256(aig_path),
        "aig_graph_sha256": graph["graph_sha256"],
        "feature_node_count": len(graph["nodes"]),
    }
    for key, value in expected.items():
        if mapping.get(key) != value:
            raise ValueError("Anchor AIG mapping mismatch for {}".format(key))
    lowered = lower_to_anchor_aig(source_path)
    if aig_path.read_text(encoding="utf-8") != lowered.text:
        raise ValueError("Anchor AIG does not match deterministic lowering")
    expected_mapping = build_aigmap(
        source_path, aig_path, lowered, graph, recorded_aig_path=expected_aig_path
    )
    if mapping.keys() != expected_mapping.keys():
        raise ValueError("Anchor AIG mapping has missing or unexpected fields")
    for key, value in expected_mapping.items():
        if key in AUDIT_PATH_FIELDS:
            if not isinstance(mapping.get(key), str) or not mapping[key].strip():
                raise ValueError("Anchor AIG mapping has invalid audit path {}".format(key))
        elif mapping.get(key) != value:
            raise ValueError("Anchor AIG mapping mismatch for {}".format(key))
    rows = [record["anchor_node"] for record in mapping["signals"].values()]
    if len(rows) != len(set(rows)):
        raise ValueError("Original signals do not have unique AIG anchors")
    return lowered.source


def write_json(path, value):
    Path(path).write_text(
        json.dumps(value, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
